# (string) Title of your wiki
title: Tsao-lab Wiki
demo_ver: 1.0.22
remote_theme: Drassil/git-wiki-theme@master
description: Welcome to Tsao-lab Wiki!
show_downloads: true
show_wiki_pages: false
show_wiki_pages_limit: 0
paginate: 2
paginate_path: "/assets/blog/page:num"
permalink: "/assets/blog/posts/:year/:month/:day/:title:output_ext"
blog_feature: true
show_wiki_posts: true
show_wiki_posts_limit: 10
logo_url: assets/images/monkey-grooming.png
google_analytics:
git_branch: master
use_github_wiki: false
use_prose_io: false
service: github
search_engine : "github"
google_cse_token: 
wiki_folder : "wiki"
site_root: 

#
# Jekyll
#

defaults:
 - 
    scope:
      path: "wiki"
    values:
      permalink: /:basename
 -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "git-wiki-default"
 -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "git-wiki-default"
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "git-wiki-post"
 -
    scope:
      path: assets/blog
    values:
      layout: "git-wiki-blog"

plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
  
#
# INCLUDING HOOKS
# They are optional, change them only if you need
# Check wiki documentation to learn how they work
#

inc_after_content: "drassil/comments.html"
inc_after_head : "drassil/head.html"
inc_before_page_list : "drassil/sidebar.html"
